"""rename Task column from `done` to `completed`

Revision ID: 547713c4d506
Revises: 5ee218c97f8
Create Date: 2015-11-09 16:55:01.710945

"""

# revision identifiers, used by Alembic.
revision = '547713c4d506'
down_revision = '5ee218c97f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('task', 'done')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task', 'completed')
    ### end Alembic commands ###
