"""make `body` field on Task model non nullable

Revision ID: 5bb6f9a53d7
Revises: 52e599f19351
Create Date: 2015-11-10 14:29:15.011163

"""

# revision identifiers, used by Alembic.
revision = '5bb6f9a53d7'
down_revision = '52e599f19351'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
